# frozen_string_literal: true

source 'https://rubygems.org'

source 'https://gems.cloud.bbc.co.uk' do
  gem 'aws-helper-v2'
  gem 'ispy', '>= 14'
  gem 'mod_av_cucumber'
end

source 'https://rubygems.org' do
  gem 'erubis'
  gem 'rest-assured'
  gem 'rest-client'
  gem 'sqlite3'

  group :local do
    gem 'pry'
  end

  group :development do
    gem 'rubocop'
  end
end
