# frozen_string_literal: true

source 'https://gems.cloud.bbc.co.uk' do
  gem 'aws-helper-v2', '>= 7.5'
  gem 'ispy', '>= 12'
  gem 'mod_av_cucumber'
end

source 'https://rubygems.org' do
  gem 'erubis'
  gem 'rest-client'

  group :local do
    gem 'pry'
  end

  group :development do
    gem 'rubocop'
  end
end
